yolo_model:

  config_file:
    name: yolov3-tiny-MBZIRC-valid.cfg
  weight_file:
    name: yolov3-tiny-MBZIRC_3000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - balloon
      - aircraft 
